# Generated by Django 5.2.1 on 2025-06-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_event_date_postevent_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postevent',
            name='title',
            field=models.TextField(default='Epic event!'),
        ),
    ]
