# Generated by Django 5.2.1 on 2025-06-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postevent_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimageurl',
            name='url',
        ),
        migrations.RemoveField(
            model_name='postvideourl',
            name='url',
        ),
        migrations.AddField(
            model_name='postimageurl',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AddField(
            model_name='postvideourl',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='post_videos/'),
        ),
    ]
