# Generated by Django 5.2.1 on 2025-06-30 07:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_postimageurl_url_remove_postvideourl_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcommentpic',
            name='url',
        ),
        migrations.RemoveField(
            model_name='postcommentreplypic',
            name='url',
        ),
        migrations.AddField(
            model_name='postcommentpic',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='postcommentreplypic',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='comment_reply_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='postcommentreply',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
