# Generated by Django 5.2.1 on 2025-07-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_postcommentpic_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='created_at',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='updated_at',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postcommentreply',
            name='created_at',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postcommentreply',
            name='updated_at',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
