# Generated by Django 5.2.1 on 2025-06-16 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, help_text='e.g., Prepare the Glass', max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipe_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='recipe_videos/')),
                ('receipe_steps', models.JSONField(blank=True, help_text='adding steps')),
                ('alcohol_content', models.FloatField(help_text='Alcohol percentage (e.g., 20 for 20%)')),
                ('flavor_profile', models.CharField(blank=True, max_length=50)),
                ('drink_strength', models.CharField(blank=True, help_text='e.g., Light, Medium, Strong', max_length=50)),
                ('glass_type', models.CharField(blank=True, max_length=50)),
                ('rating', models.FloatField(default=0.0, help_text='Average rating out of 5')),
                ('review_count', models.PositiveIntegerField(default=0, help_text='Number of reviews')),
                ('servings', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('coctail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cocktails.cocktail')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('coctail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cocktails.cocktail')),
            ],
        ),
    ]
