# Generated by Django 5.2.1 on 2025-06-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='alcohol_content',
            field=models.FloatField(blank=True, help_text='Alcohol percentage (e.g., 20 for 20%)', null=True),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, help_text='Average rating out of 5', null=True),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='receipe_steps',
            field=models.JSONField(blank=True, help_text='adding steps', null=True),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='servings',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
