# Generated by Django 5.2.1 on 2025-06-18 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_alter_cocktail_alcohol_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='coctail',
            new_name='cocktail',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='coctail',
            new_name='cocktail',
        ),
    ]
