# Generated by Django 5.2.1 on 2025-06-18 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0004_alter_ingredient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='receipe_steps',
        ),
        migrations.AddField(
            model_name='cocktail',
            name='recipe_steps',
            field=models.JSONField(blank=True, help_text='List of steps', null=True),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='title',
            field=models.CharField(blank=True, help_text='e.g., Margarita', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cocktail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='cocktails.cocktail'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
