# Generated by Django 5.2.1 on 2025-06-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_chatmessage_sender_remove_chatroom_mates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessageimageurl',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to='chat'),
        ),
    ]
