# Generated by Django 5.2.1 on 2025-06-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chatmessageimageurl_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessageimageurl',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
